### ISSUE TITLE
Bootstrap Functions added twice

### ISSUE THREAD

**Issue by hsankala** [webpixels/css#21]
In [css/src/core/_index.scss](https://github.com/webpixels/css/blob/bcfd10ac36371ed428e67279c8f89d04a89f79ab/src/core/_index.scss) we import the WebPixels functions.

https://github.com/webpixels/css/blob/bcfd10ac36371ed428e67279c8f89d04a89f79ab/src/core/_index.scss#L2

The first thing the custom functions file does is import the bootstrap functions:
https://github.com/webpixels/css/blob/bcfd10ac36371ed428e67279c8f89d04a89f79ab/src/core/_functions.scss#L7

Then further on in the core index.scss file we pull in the bootstrap functions again: 
https://github.com/webpixels/css/blob/bcfd10ac36371ed428e67279c8f89d04a89f79ab/src/core/_index.scss#L8

**Comment by alexisenache** [comment]
Thanks, @hsankala. I fixed it in v1.2.2.
